In [3]:
import numpy as np
print(np.__version__)

2.3.2


In [7]:
import numpy as np    #1.basic operations
#
arr1=np.array([1,2,3,4,5])  #from list
print(arr1)

arr2=np.array([[1,2,3],[4,5,6]])  #multi-dimensional
print(arr2)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
