In [ ]:
import numpy as np       # 1.creating arrays

#from list 1d
arr1=np.array([1,2,3,4,5])       
print(arr1)

In [10]:
#multi-dimensional array 2d
arr2=np.array([[1,2,3],[4,5,6]]) #multi-dimensional array 2d
print(arr2)

[[1 2 3]
 [4 5 6]]


In [12]:
#special arrays
arr_zeros=np.zeros((3,4))        #3*4 array of zeros
arr_ones=np.ones((4,2))          #4*2 array of ones
arr_empty=np.empty((4,4))        #4*4 arry of unintialized values(garbage values) - empty array
arr_full=np.full((3,4),7)        #3*4 array filled with 7

print(arr_zeros)
print(arr_ones)
print(arr_empty)
print(arr_full)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[6.23042070e-307 4.67296746e-307 1.69121096e-306 2.22512818e-307]
 [1.89146387e-307 2.33646676e-307 1.86921143e-306 6.89813979e-307]
 [1.60218491e-306 1.02360867e-306 1.69122046e-306 1.86921958e-306]
 [6.89804133e-307 1.11261162e-306 8.34443015e-308 2.22813476e-312]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [16]:
#sequences
arr_seq=np.arange(0,10,2)       #similar to range()
arr_linesp=np.linspace(0,1,10)  #10 spaced values between 0 to 1

print(arr_seq)
print(arr_linesp)

[0 2 4 6 8]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [18]:
#identity matrix
arr_iden=np.eye(4)   #4*4 I
print(arr_iden)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [66]:
#random arrays
arr_random=np.random.rand(3,3)  #3*3 random float no's between [0,1) - uniform distribution
print(arr_random)
arr_randi=np.random.randint(0,100,(3,3)) #3*3 of random integers
print(arr_randi)
arr_normal=np.random.randn(3,3)     #3*3 of standared normal distribution
print(arr_normal)

[[0.83979119 0.80330794 0.38967887]
 [0.52130013 0.290747   0.20788465]
 [0.03121388 0.59506157 0.74065202]]
[[39 86 81]
 [72 63 43]
 [56  6 99]]
[[-0.15671669 -0.36968337  0.07499928]
 [-1.48346223  0.09905481 -1.34612895]
 [ 0.31612872 -0.09694751 -0.94402748]]


In [54]:
#2.array properties
arr3=np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr3.shape)  #2*5 dimension
print(arr3.size)   #10 total elements
print(arr3.ndim)   #2 dimensions
print(arr3.dtype)  #int64 - data type
print(arr3.itemsize) #8 bytes per element
print(arr3.nbytes)   #total arrayt of 80 bytes

(2, 5)
10
2
int64
8
80


In [45]:
#3. data types
#explicit data type specification
arr_int=np.array([1,2],dtype=np.int32)  
arr_float=np.array([1,5,4],dtype=np.float64)
arr_complex=np.array([5,45,36],dtype=np.complex128)
arr_bool=np.array([1,45,63],dtype=np.bool_)

print(arr_int,arr_int.dtype)
print(arr_float,arr_float.dtype)
print(arr_complex,arr_complex.dtype)
print(arr_bool,arr_bool.dtype)

#type conversion
arr_con=np.array([1,54,78])
arr_flo=arr_con.astype(np.float64)
print(arr_flo)

[1 2] int32
[1. 5. 4.] float64
[ 5.+0.j 45.+0.j 36.+0.j] complex128
[ True  True  True] bool
[ 1. 54. 78.]


In [68]:
import os
os.getcwd()

'C:\\Users\\B DIVYA SREE\\numpy_learning'