In [1]:
import numpy as np
#1.basic indexing
arr1=np.array([10,20,30,40,50])   #1d
print(arr1[1])  #positive indexing
print(arr1[-2]) #negitive indexing

arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])  #2d
print(arr2[1])
print(arr2[1,3])

20
40
[ 6  7  8  9 10]
9


In [33]:
#2.slicing
arr2=np.array([1,2,45,3,65,23,4,5,96])   #1d
print(arr2[2:8])   #includes 2,excludes 8
print(arr2[:5])    
print(arr2[2:])
print(arr2[::2])   #every 2nd value
print(arr2[::-2])  #reversed array with every 2nd value

arr3=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])   #2d
print(arr3[0:2,1:4])   #rows - 0 to 1, columns - 1 to 3
print(arr3[:,1:3])       #all rows, only column 1,2
print(arr3[0:2,:])       #only row 0,1, all columns

[45  3 65 23  4  5]
[ 1  2 45  3 65]
[45  3 65 23  4  5 96]
[ 1 45 65  4 96]
[96  4 65 45  1]
[[2 3 4]
 [7 8 9]]
[[ 2  3]
 [ 7  8]
 [12 13]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [63]:
#boolean and fancy indexing
arr4=np.array([1,45,85,4,3,2,56,8,6])
bool_index=arr4>3   #boolean indexing- array of bools depending the given crireria
print(bool_index)
print(arr4[bool_index])  #return true values

print((arr4>3)&(arr4<80))   #multiple conditions - dont't forget to use braces
print(arr4[(arr4>3)&(arr4<80)])

indices=[0,2,3,5,6]     #using array of indices
print(arr4[indices])

arr5=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])   #2d
rows=[0,2]
cols=[1,2]
print(arr5[rows,cols])

[False  True  True  True False False  True  True  True]
[45 85  4 56  8  6]
[False  True False  True False False  True  True  True]
[45  4 56  8  6]
[ 1 85  4  2 56]
[ 2 13]
