In [90]:
import numpy as np
#1.arthiemtic operations
arr1=np.array([1,2,3,4,5])
arr2=np.array([7,8,9,10,6])
print(arr1+arr2)  #element-wise operations
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1**arr2)
print(arr1%2)

#broadcasting
print(arr1+10)  #arr1+[10,10,10,10,10]-automatically does it
print(arr2*2)

[ 8 10 12 14 11]
[-6 -6 -6 -6 -1]
[ 7 16 27 40 30]
[0.14285714 0.25       0.33333333 0.4        0.83333333]
[      1     256   19683 1048576   15625]
[1 0 1 0 1]
[11 12 13 14 15]
[14 16 18 20 12]


In [92]:
#2.matrix opearations
arr_mat1=np.array([[1,2],[4,5]])
arr_mat2=np.array([[7,8],[10,11]])
print(arr_mat1*arr_mat2)             #element-wise multiply
print(np.matmul(arr_mat1,arr_mat2))   #matrix mutiplication  (arr_mat1@arr_mat2 is the modern way)
print(np.dot(arr_mat1,arr_mat2))      #old way

print(arr_mat1.T)                #transpose 
print(np.linalg.det(arr_mat2))   #determinant
print(np.linalg.inv(arr_mat1))   #inverse
print(np.linalg.eig(arr_mat2))   #eigen values and eigen vectors

[[ 7 16]
 [40 55]]
[[27 30]
 [78 87]]
[[27 30]
 [78 87]]
[[1 4]
 [2 5]]
-2.9999999999999902
[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]
EigResult(eigenvalues=array([-0.16515139, 18.16515139]), eigenvectors=array([[-0.74490545, -0.58243756],
       [ 0.66717004, -0.81287544]]))


In [94]:
#3.statistical opeartions
arr3=np.array([[1,5,56],[2,45,96],[85,75,92]])
print(np.sum(arr3))        #sum of all elements
print(np.sum(arr3,axis=0))  #sum of cols(axis=0)
print(np.sum(arr3,axis=1))  #sum of rows(axis=1)
print(np.mean(arr3))        #mean
print(np.std(arr3))         #standard deviation
print(np.var(arr3))         #variance
print(np.min(arr3))         #minimum value
print(np.max(arr3))         #maximum value
print(np.median(arr3))      #median value

#cumulative operations
print(np.cumsum(arr3))       #cumulative sum
print(np.cumprod(arr3))      #cumulative product

457
[ 88 125 244]
[ 62 143 252]
50.77777777777778
37.290981268272056
1390.617283950617
1
96
56.0
[  1   6  62  64 109 205 290 365 457]
[            1             5           280           560         25200
       2419200     205632000   15422400000 1418860800000]
